### ISSUE TITLE
Release v1.2.0 seems to be broken

### ISSUE THREAD

**Issue by teroyks** [JasonEtco/rss-to-readme#11]
Trying to use the latest release results in the following error message:
`File not found: '/home/runner/work/_actions/JasonEtco/rss-to-readme/v1.2.0/dist/index.js'`

Looking at the Actions tab, building v1.2.0 has an error.

**Comment by JasonEtco** [comment]
Should be good now, thanks for letting me know! Released a couple versions while fixing stuff, 1.2.5 should be good to go.
