### ISSUE TITLE
Branch not respected by readme-box

### ISSUE THREAD

**Issue by aaronpowell** [JasonEtco/rss-to-readme#12]
Thanks for merging #10 but there still seems to be an issue. Here's a job run explicitly against `v1.2.5` - https://github.com/aaronpowell/aaronpowell/runs/2007910650?check_suite_focus=true

It fails because it still tried to use `master` as the branch, even though the branch is explicitly set to `main` (https://github.com/aaronpowell/aaronpowell/runs/2007910650?check_suite_focus=true#step:2:5).

Digging through the code, it seems the problem is with [readme-box](https://github.com/JasonEtco/readme-box) not respecting the branch option being passed on https://github.com/JasonEtco/rss-to-readme/blob/main/src/index.ts#L35

If you look at the `v0.1.2` release of the package, and when it tries to update the readme (https://github.com/JasonEtco/readme-box/blob/v0.1.2/src/index.ts#L93) it's not respecting the provided branch, it's hardcoded with `master`. That was fixed with https://github.com/JasonEtco/readme-box/commit/a200e2e0a61623d4db7430043032628994fc5ed0 but it looks like a new npm package hasn't been released with those changes (see the bundled version https://github.com/JasonEtco/rss-to-readme/blob/v1.2.5/dist/index.js#L1393).

Looks like https://github.com/JasonEtco/readme-box/issues/5 just needs to be closed and a new version pushed, then for this Action to use the new version.

**Comment by JasonEtco** [comment]
👋 thanks for letting me know @aaronpowell - as you've no doubt seen from the many releases today, there have been a bunch of issues 😓 thanks for all of the links and details. I've just published `v0.2.0` of `readme-box` and opened #13 to get it updated here. I'll publish `v1.2.6` of this Action shortly - it'd be great if you could give it a look and see if it works for you 🙏

**Comment by aaronpowell** [comment]
I can confirm it works! https://github.com/aaronpowell/aaronpowell/runs/2008577711?check_suite_focus=true

**Comment by JasonEtco** [comment]
Thank you for checking! And thanks for poking @bnb to grab my attention here, I'm glad to get it working a little bit better 🙌
