### ISSUE TITLE
Only works with `master` as main branch

### ISSUE THREAD

**Issue by teroyks** [JasonEtco/rss-to-readme#9]
This action only works with old-style repositories where the main branch is called `master`.

Suggested fix: add a config option `branch` that would pass the value on to README Box.

**Comment by JasonEtco** [comment]
👋 thanks for the issue - I totally agree, a `branch` option would be great. If you're up for a PR, here's what it would look like:

* A change to the `Inputs` type:

https://github.com/JasonEtco/rss-to-readme/blob/3bff2c7baa56cf8add1cd26e9dc6bed17b4e46e4/src/index.ts#L8-L14

* Use it here, as `branch: this.inputs.branch`:

https://github.com/JasonEtco/rss-to-readme/blob/3bff2c7baa56cf8add1cd26e9dc6bed17b4e46e4/src/index.ts#L30-L34

* Update the `action.yml` file and `README.md`:

https://github.com/JasonEtco/rss-to-readme/blob/3bff2c7baa56cf8add1cd26e9dc6bed17b4e46e4/action.yml#L3

**Comment by teroyks** [comment]
Ok, created [one](https://github.com/JasonEtco/rss-to-readme/pull/10). Unfortunately I’m unable to test it so hopefully everything is ok.

**Comment by JasonEtco** [comment]
Closed by #10 🎉
